### ISSUE TITLE
Should we use CookieCutter instead?

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/ladybug-tools-template#2]
I'm assuming this is a cookicutter project. If this is the case I don't think the current set up works. You will need to nest the project into another folder. The top level is meant to cover all the cookie cutter meta data and the folder with `{{project.name}}` contains all the stuff that will be generated when calling cookie cutter.

**Comment by mostaphaRoudsari** [comment]
It is not a cookie-cutter project. It uses GitHub's template repository idea and the changes is done with a simple find + replace. I checked cookie-cutter and it looked like too much for what we need but I admit that I can be totally wrong! So you tell me - does this work?

**Comment by AntoineDao** [comment]
If it's not cookie cutter then I have no idea. However I have found cookie cutter very straightforward to setup so could show you a demo version in a PR at some point this week if you fancy it.

**Comment by mostaphaRoudsari** [comment]
sounds like a plan! I found GitHub's template repository handy but if cookie-cutter offers a better solution then we should switch.
