### ISSUE TITLE
Include `pip install -r requirements.txt` in travis.yml

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-tools-template#4]
It seems that the default travil.yml only installs `dev-requirements.txt` and not `requirements.txt`. So we need to add the following line:
```
pip install -r requirements.txt
```
... to this part of the template:
https://github.com/ladybug-tools/ladybug-tools-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.travis.yml#L26

**Comment by chriswmackey** [comment]
It looks like we also need to add it here:
https://github.com/ladybug-tools/ladybug-tools-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.travis.yml#L8

**Comment by mostaphaRoudsari** [comment]
Makes sense to me. @AntoineDao what do you think about this?

Also I remember that I had to remove a similar line since the file was empty and that made pip crash. Didn't do enough search at the time to see what is the best solution in such cases.

**Comment by chriswmackey** [comment]
Ah. That makes sense why you would put it there. But I think a lot of the new ladybug tools repos we create will have dependencies on other ladybug tools repos.  Is there a way to ask for an input of dependencies in the setup of the cookie cutter template? If not, maybe we should initialize the template with a dependency already in requirements.txt so that it doesn't crash pip. People can always change it to be something else later.

**Comment by AntoineDao** [comment]
I'll sort it just now 😄
