### ISSUE TITLE
Separte documentation step from deployment in travis.yml

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-tools-template#7]
I noticed that we haven't updated travis file in this repository. We should update this before the workshop tomorrow. I will do it tonight if no one else does it before me.

**Comment by chriswmackey** [comment]
I'll be on it!

**Comment by chriswmackey** [comment]
Being addressed via https://github.com/ladybug-tools/ladybug-tools-template/pull/8

**Comment by chriswmackey** [comment]
Done!
